import { chromium } from "playwright";
const exe = "/root/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome";
const browser = await chromium.launch({ executablePath: exe });
const ctx = await browser.newContext({ viewport: { width: 430, height: 900 }, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const logs = [];
page.on("console", (m) => logs.push(`[${m.type()}] ${m.text()}`));
page.on("pageerror", (e) => logs.push(`[pageerror] ${e.message}`));
const brand = () => page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--brand-a").trim());
const heading = () => page.evaluate(() => document.querySelector("h1,h2")?.textContent?.trim());
await page.goto("http://localhost:4173/", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
await page.tap("body");
await page.waitForTimeout(1000);
console.log("on:", await heading(), "| brand-a:", await brand());
await page.getByText("Birthday", { exact: true }).tap();
await page.waitForTimeout(700);
console.log("after tap Birthday -> heading:", await heading(), "| brand-a:", await brand());
await page.getByText("Continue", { exact: true }).tap();
await page.waitForTimeout(1200);
console.log("after Continue -> heading:", await heading());
console.log("\nlogs:\n" + (logs.join("\n") || "(none)"));
await browser.close();
