import { chromium } from "playwright";
const exe = "/root/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome";
const browser = await chromium.launch({ executablePath: exe });
const ctx = await browser.newContext({ viewport: { width: 430, height: 900 }, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", (e) => errs.push("[pageerror] " + e.message));
const txt = () => page.evaluate(() => document.body.innerText.replace(/\n+/g,' | ').slice(0,90));
const tap = async (sel) => { const b = await page.getByRole("button", { name: sel }).first().boundingBox(); await page.touchscreen.tap(b.x+b.width/2, b.y+b.height/2); };
await page.goto("http://localhost:4173/", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
console.log("1 welcome:", await txt());
await page.tap("body"); await page.waitForTimeout(1000);
console.log("2 theme:", await txt());
await page.getByText("Birthday", { exact: true }).tap(); await page.waitForTimeout(400);
await tap("Continue"); await page.waitForTimeout(1000);
console.log("3 layout:", await txt());
await page.getByText("4 Grid", { exact: true }).tap(); await page.waitForTimeout(400);
await tap("Start shooting"); await page.waitForTimeout(1200);
console.log("4 capture:", await txt());
console.log("errors:", errs.join(" ") || "none");
await browser.close();
