import { chromium } from "playwright";
const exe = "/root/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome";
const browser = await chromium.launch({ executablePath: exe });
const ctx = await browser.newContext({ viewport: { width: 430, height: 900 }, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
page.on("console", (m) => { if (m.text().includes("[go]")) console.log("  console:", m.text()); });
page.on("pageerror", (e) => console.log("  PAGEERROR:", e.message));
const scr = () => page.evaluate(() => window.__session.getState().screen);
await page.goto("http://localhost:4173/", { waitUntil: "networkidle" });
await page.waitForTimeout(2500);
console.log("store.screen:", await scr());
await page.tap("body"); await page.waitForTimeout(1000);
console.log("after welcome tap -> store.screen:", await scr());
await page.getByText("Birthday", { exact: true }).tap(); await page.waitForTimeout(400);
const b = await page.getByRole("button", { name: "Continue" }).boundingBox();
console.log("Continue box y:", b.y, "height:", b.height, "(viewport 900)");
await page.touchscreen.tap(b.x+b.width/2, b.y+b.height/2);
await page.waitForTimeout(1200);
console.log("after Continue -> store.screen:", await scr());
await browser.close();
